### ISSUE TITLE
Can not get demo to work at all

### ISSUE THREAD

**Issue by lerokko** [AndrewChubatiuk/nomad-hcloud-autoscaler#12]
I setup a fresh Hetzner project with a fresh instance + api key and installed terraform on it and cloned this repo.
I do `terrform init` in `demo/setup` with no errors
Then I run `terraform plan` as instructed:

- CX11 is deprecated you can order them via ap but hetzner begs you desperately to rescale it to at least CX22.
- It gets stuck on `"waiting for cloud init"`
- If that check is commented out in wait.sh it gets stuck on `"waiting for nomad"`
- I have let it wait for over 3 hours its definitely not working

I am using a CAX11 (ARM based, cheapest instance) instance with ubuntu 24.04

AM I an idiot? I see no dependencies/prerequisites listed in the doku/readme. Is this plugin just broken, or am I?
It is the one that is linked in the official Hashicorp doku.

**Comment by AndrewChubatiuk** [comment]
Hey @lerokko
As it's mentioned in [hashicorp docs](https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/external), this project is a community one and not officially maintained by hashicorp developers. I've built it, but it's not frequently maintained, as I'm not working with Nomad at the moment

Regarding deprecated CX11 type you might notice it was deprecated this summer and terraform module was not updated for more than a year. You can submit a PR to fix this if you want

Also if you've spent some time to understand why demo is not working, you could notice, that [custom autoscaler image](https://github.com/AndrewChubatiuk/nomad-hcloud-autoscaler/blob/ab7164cc03b3ffbc34a87f9b6b25fd08871a0f79/demo/setup/jobs/autoscaler.hcl#L17C23-L17C50) with plugin was built for [linux/amd64](https://hub.docker.com/r/achubatiuk/nomad-autoscaler/tags), so it's expected, that it's not running on CAX11

I understand your disappointment, but I don't have time to fix it at the moment, also my Hetzner account was locked due to inactivity. If you manage to fix it - feel free to submit a PR or you can wait till I'll do it

**Comment by lerokko** [comment]
Thank you for your reply. That is okay. I have given up. This is no longer needed by me, Godspeed
